"""Test trained W2V classifier on test data set.

Usage:
  testw2v.py --in-data=<testdata> --out-classes=<testclasses> --model=<w2vmodel> --prog-classifier=<classifier> --cancer-classifier=<classifier>

Options:
  --in-data=<testdata>             Input file with cleaned radiology reports (as generated by `cleaning.py`)
  --out-classes=<testclasses>      Output file with produced classifications.
  --model=<w2vmodel>               W2v model (generated by `buildw2v.py`)
  --prog-classifier=<classifier>   Progression classifier (generated by `trainw2v.py`)
  --cancer-classifier=<classifier> Cancer classifier (generated by `trainw2v.py`)
"""
from docopt import docopt

import csv

from helpers import getEncoding
from classifiers import W2VClassifier

if __name__ == '__main__':
    arguments = docopt(__doc__)

    inFilename = arguments['--in-data']
    outFilename = arguments['--out-classes']
    w2vModelFile = arguments['--model']
    c_classifier_file = arguments['--prog-classifier']
    p_classifier_file = arguments['--cancer-classifier']

    print('Loading classifier...')
    w2v = W2VClassifier(w2vModelFile, c_classifier_file, p_classifier_file)

    print('Classifying reports...')
    encoding=getEncoding(inFilename)
    with open(inFilename, 'r', encoding=encoding) as infile:
        csvreader = csv.reader(infile, delimiter=',')

        with open(outFilename, 'w') as outfile:
            writer = csv.writer(outfile, quoting=csv.QUOTE_NONNUMERIC)
            for idx, report in csvreader:
                c_class, p_class = w2v.classify(report)
                writer.writerow([int(idx), c_class, p_class])
