"""Test trained FLAIR classifier on test data set.

Usage:
  testflair.py --in-data=<testdata> --out-classes=<testclasses> --prog-classifier=<classifier> --cancer-classifier=<classifier>

Options:
  --in-data=<testdata>             Input file with cleaned radiology reports (as generated by `cleaning.py`)
  --out-classes=<testclasses>      Output file with produced classifications.
  --prog-classifier=<classifier>   Progression classifier (generated by `trainflair.py`)
  --cancer-classifier=<classifier> Cancer classifier (generated by `trainflair.py`)
"""
from docopt import docopt

import csv

from helpers import getEncoding
from classifiers import FlairClassifier

if __name__ == '__main__':
    arguments = docopt(__doc__)

    inFilename = arguments['--in-data']
    outFilename = arguments['--out-classes']
    c_classifier_file = arguments['--prog-classifier']
    p_classifier_file = arguments['--cancer-classifier']

    print('Loading classifier...')
    flair = FlairClassifier(c_classifier_file, p_classifier_file)

    print('Classifying reports...')
    encoding=getEncoding(inFilename)
    with open(inFilename, 'r', encoding=encoding) as infile:
        csvreader = csv.reader(infile, delimiter=',')

        with open(outFilename, 'w') as outfile:
            writer = csv.writer(outfile, quoting=csv.QUOTE_NONNUMERIC)
            for idx, report in csvreader:
                c_class, p_class = flair.classify(report)
                writer.writerow([int(idx), c_class, p_class])
                print('.',end='', flush=True)
